"""The 15 covered countries and their official sources."""
from __future__ import annotations

COUNTRIES: dict[str, dict] = {
    "TJ": {"ru": "Таджикистан", "en": "Tajikistan", "currency": "TJS"},
    "UZ": {"ru": "Узбекистан", "en": "Uzbekistan", "currency": "UZS"},
    "KG": {"ru": "Кыргызстан", "en": "Kyrgyzstan", "currency": "KGS"},
    "KZ": {"ru": "Казахстан", "en": "Kazakhstan", "currency": "KZT"},
    "TM": {"ru": "Туркменистан", "en": "Turkmenistan", "currency": "TMT"},
    "AF": {"ru": "Афганистан", "en": "Afghanistan", "currency": "AFN"},
    "RU": {"ru": "Россия", "en": "Russia", "currency": "RUB"},
    "BY": {"ru": "Беларусь", "en": "Belarus", "currency": "BYN"},
    "UA": {"ru": "Украина", "en": "Ukraine", "currency": "UAH"},
    "MD": {"ru": "Молдова", "en": "Moldova", "currency": "MDL"},
    "AZ": {"ru": "Азербайджан", "en": "Azerbaijan", "currency": "AZN"},
    "PL": {"ru": "Польша", "en": "Poland", "currency": "PLN"},
    "CZ": {"ru": "Чехия", "en": "Czechia", "currency": "CZK"},
    "DE": {"ru": "Германия", "en": "Germany", "currency": "EUR"},
    "LT": {"ru": "Литва", "en": "Lithuania", "currency": "EUR"},
}

# Source registry. `code` is the collector name (see server/scrapers/__init__.py).
SOURCES: list[dict] = [
    {"code": "tj_zakupki", "country": "TJ", "name": "zakupki.gov.tj", "url": "https://zakupki.gov.tj",
     "publisher_ru": "Агентство по госзакупкам при Правительстве РТ", "publisher_en": "Public Procurement Agency under the Government of Tajikistan",
     "kind": "html"},
    {"code": "uz_xarid", "country": "UZ", "name": "xarid.uzex.uz", "url": "https://xarid.uzex.uz",
     "publisher_ru": "Узбекская республиканская товарно-сырьевая биржа", "publisher_en": "Uzbek Republican Commodity Exchange",
     "kind": "api"},
    {"code": "kg_zakupki", "country": "KG", "name": "zakupki.gov.kg", "url": "https://zakupki.gov.kg",
     "publisher_ru": "Портал государственных закупок КР", "publisher_en": "Public procurement portal of the Kyrgyz Republic",
     "kind": "api"},
    {"code": "kz_goszakup", "country": "KZ", "name": "goszakup.gov.kz", "url": "https://goszakup.gov.kz",
     "publisher_ru": "Портал госзакупок Министерства финансов РК", "publisher_en": "Public procurement portal of the Ministry of Finance of Kazakhstan",
     "kind": "api"},
    {"code": "ungm_tm", "country": "TM", "name": "ungm.org", "url": "https://www.ungm.org/Public/Notice",
     "publisher_ru": "Тендеры агентств ООН и международных организаций в Туркменистане (единого национального портала нет)",
     "publisher_en": "UN agencies and international organisations' tenders for Turkmenistan (no single national portal)",
     "kind": "api"},
    {"code": "ungm_af", "country": "AF", "name": "ungm.org", "url": "https://www.ungm.org/Public/Notice",
     "publisher_ru": "Тендеры агентств ООН и международных организаций; национальный портал NPA",
     "publisher_en": "UN agencies and international organisations' tenders; national portal NPA",
     "kind": "api"},
    {"code": "ru_zakupki", "country": "RU", "name": "zakupki.gov.ru", "url": "https://zakupki.gov.ru",
     "publisher_ru": "Единая информационная система в сфере закупок (44-ФЗ, 223-ФЗ)", "publisher_en": "Unified procurement information system (44-FZ, 223-FZ)",
     "kind": "rss"},
    {"code": "by_icetrade", "country": "BY", "name": "icetrade.by", "url": "https://icetrade.by",
     "publisher_ru": "Информационная система «Тендеры» Национального центра маркетинга", "publisher_en": "ICETRADE, National Centre for Marketing",
     "kind": "html"},
    {"code": "ua_prozorro", "country": "UA", "name": "prozorro.gov.ua", "url": "https://prozorro.gov.ua",
     "publisher_ru": "Prozorro, открытый API центральной базы данных", "publisher_en": "Prozorro central database public API",
     "kind": "api"},
    {"code": "md_mtender", "country": "MD", "name": "mtender.gov.md", "url": "https://mtender.gov.md",
     "publisher_ru": "MTender, открытые данные Министерства финансов РМ", "publisher_en": "MTender open data, Ministry of Finance of Moldova",
     "kind": "api"},
    {"code": "az_etender", "country": "AZ", "name": "etender.gov.az", "url": "https://etender.gov.az",
     "publisher_ru": "Единый интернет-портал госзакупок Азербайджана", "publisher_en": "Unified public procurement portal of Azerbaijan",
     "kind": "api"},
    {"code": "pl_bzp", "country": "PL", "name": "ezamowienia.gov.pl", "url": "https://ezamowienia.gov.pl",
     "publisher_ru": "Biuletyn Zamówień Publicznych, открытый API", "publisher_en": "Public Procurement Bulletin (BZP) open API",
     "kind": "api"},
    {"code": "ted_cz", "country": "CZ", "name": "ted.europa.eu", "url": "https://ted.europa.eu",
     "publisher_ru": "Официальный журнал ЕС (TED), извещения по Чехии; национальный портал NEN", "publisher_en": "Tenders Electronic Daily (EU), notices for Czechia; national portal NEN",
     "kind": "api"},
    {"code": "ted_de", "country": "DE", "name": "ted.europa.eu", "url": "https://ted.europa.eu",
     "publisher_ru": "Официальный журнал ЕС (TED), извещения по Германии", "publisher_en": "Tenders Electronic Daily (EU), notices for Germany",
     "kind": "api"},
    {"code": "ted_lt", "country": "LT", "name": "ted.europa.eu", "url": "https://ted.europa.eu",
     "publisher_ru": "Официальный журнал ЕС (TED), извещения по Литве; национальный портал CVP IS", "publisher_en": "Tenders Electronic Daily (EU), notices for Lithuania; national portal CVP IS",
     "kind": "api"},
]

SOURCE_BY_CODE = {s["code"]: s for s in SOURCES}
